CREATE TABLE USERS
(
    ID        BIGSERIAL PRIMARY KEY,
    PASSWORD  VARCHAR NOT NULL,
    USERNAME  VARCHAR NOT NULL UNIQUE,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME  VARCHAR NOT NULL,
    ROLES     VARCHAR NOT NULL);

CREATE TABLE DOZENT(
                       ID BIGINT PRIMARY KEY,
                       CONSTRAINT FK_DOZENT_USERS FOREIGN KEY (ID) REFERENCES USERS (ID));

CREATE TABLE UMSCHULER(
                          ID BIGINT PRIMARY KEY,
                          CONSTRAINT FK_UMSCHULER_USERS FOREIGN KEY (ID) REFERENCES USERS (ID));

CREATE TABLE VERWALTUNG(
                           ID BIGINT PRIMARY KEY,
                           CONSTRAINT FK_VERWALTUNG_USERS FOREIGN KEY (ID) REFERENCES USERS (ID));

CREATE TABLE ANWESENHEIT(
                            ID           BIGSERIAL PRIMARY KEY,
                            UMSCHULER_ID BIGINT    NOT NULL,
                            DATUM        TIMESTAMP NOT NULL,
                            SIGNATURE    VARCHAR   NOT NULL,
                            CONSTRAINT FK_ANWESENHEIT_UMSCHULER FOREIGN KEY (UMSCHULER_ID) REFERENCES UMSCHULER (ID));

INSERT INTO USERS(USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ROLES) values ('ugur', 'asd', 'ugur', 'oz', 'Student');
INSERT INTO USERS(USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ROLES) values ('ufuk', 'asd', 'ufuk', 'oz', 'Student');

INSERT INTO USERS(USERNAME, PASSWORD, FIRSTNAME, LASTNAME, ROLES) values ('julius', 'asd', 'julius', 'mischok', 'Teacher');


