CREATE TABLE PERSON(ID BIGSERIAL PRIMARY KEY,
                        PASSWORD VARCHAR NOT NULL,
                        FIRSTNAME VARCHAR NOT NULL,
                        LASTNAME VARCHAR NOT NULL);
CREATE TABLE DOZENT(ID BIGINT PRIMARY KEY,
                        CONSTRAINT FK_DOZENT_PERSON FOREIGN KEY(ID) REFERENCES PERSON(ID));
CREATE TABLE UMSCHULER(ID BIGINT PRIMARY KEY,
                        CONSTRAINT FK_UMSCHULER_PERSON FOREIGN KEY(ID) REFERENCES PERSON(ID));
CREATE TABLE VERWALTUNG(ID BIGINT PRIMARY KEY,
                        CONSTRAINT FK_VERWALTUNG_PERSON FOREIGN KEY(ID) REFERENCES PERSON(ID));
CREATE TABLE ANWESENHEIT(ID BIGSERIAL PRIMARY KEY,
                        UMSCHULER_ID BIGINT NOT NULL,
                        DATUM TIMESTAMP NOT NULL,
                        SIGNATURE VARCHAR NOT NULL,
                        CONSTRAINT FK_ANWESENHEIT_UMSCHULER FOREIGN KEY(UMSCHULER_ID) REFERENCES UMSCHULER(ID));
